apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: ${namespace:?}
spec:
  clusterIP: None
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    stolon-proxy: "true"
    stolon-cluster: ${namespace:?}-stolon