apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: stolon-sentinel
  namespace: ${namespace:?}
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: stolon-sentinel
        stolon-cluster: ${namespace:?}-stolon
        stolon-sentinel: "true"
    spec:
      containers:
      - name: stolon-sentinel
        image: sorintlab/stolon:master-pg9.6
        command:
          - "/bin/bash"
          - "-ec"
          - |
            exec gosu stolon stolon-sentinel
        env:
          - name: STSENTINEL_CLUSTER_NAME
            value: ${namespace:?}-stolon
          - name: STSENTINEL_STORE_BACKEND
            value: "consul"
          - name: STSENTINEL_STORE_ENDPOINTS
            value: "http://consul.kv:8500"
          - name: CONSUL_HTTP_TOKEN
            valueFrom:
              secretKeyRef:
                name: stolon-credentials
                key: CONSUL_HTTP_TOKEN