apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: stolon-proxy
  namespace: ${namespace:?}
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: stolon-proxy
        stolon-cluster: ${namespace:?}-stolon
        stolon-proxy: "true"
    spec:
      containers:
      - name: stolon-proxy
        image: sorintlab/stolon:master-pg9.6
        command:
          - "/bin/bash"
          - "-ec"
          - |
            exec gosu stolon stolon-proxy
        env:
          - name: STPROXY_CLUSTER_NAME
            value: ${namespace:?}-stolon
          - name: STPROXY_STORE_BACKEND
            value: "consul"
          - name: STPROXY_STORE_ENDPOINTS
            value: "http://consul.kv:8500"
          - name: STPROXY_LISTEN_ADDRESS
            value: "0.0.0.0"
          - name: CONSUL_HTTP_TOKEN
            valueFrom:
              secretKeyRef:
                name: stolon-credentials
                key: CONSUL_HTTP_TOKEN
        ports:
          - containerPort: 5432